### ISSUE TITLE
Getting an error for Crucible of the Cosmos

### ISSUE THREAD

**Issue by DarkBladeNemo** [STS15/Fargos-Talismans#38]
### Modpack

Yes

### Neoforge Version

21.1.90

### Mod Version

1.21-2.2.21

### Describe the issue

Everytime I reload my Kubejs I get an error in my logs for `[Worker-ResourceReload-3/ERROR] [net.minecraft.world.level.storage.loot.LootDataType/]: Couldn't parse element ResourceKey[minecraft:root / minecraft:loot_table]:fargostalismans:blocks/crucible_of_the_cosmos - Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: fargostalismans:crucible_of_the_cosmos`

I am just adding a simple shapeless recipe but for some reason this keeps appearing as a kubejs error.

`[17:21:27] [ERROR] ! RegistryAccessContainer.java#150: Failed to read result:strict_item_stack from recipe fargostalismans:blocks/crucible_of_the_cosmos[minecraft:crafting_shaped]: java.util.NoSuchElementException: No value present
[17:21:27] [ERROR] ! java.util.NoSuchElementException: No value present
[17:21:27] [ERROR] !   at java.util.Optional.orElseThrow(Optional.java:377)
[17:21:27] [ERROR] !   at …kubejs.util.RegistryAccessContainer.decodeJson(RegistryAccessContainer.java:150)
[17:21:27] [ERROR] !   at …kubejs.recipe.component.RecipeComponent.readFromJson(RecipeComponent.java:139)
[17:21:27] [ERROR] !   at …kubejs.recipe.KubeRecipe.deserialize(KubeRecipe.java:78)
[17:21:27] [ERROR] !   at …kubejs.recipe.schema.RecipeSchema.deserialize(RecipeSchema.java:255)
[17:21:27] [ERROR] !   at …kubejs.recipe.RecipesKubeEvent.parseOriginalRecipe(RecipesKubeEvent.java:241)
[17:21:27] [ERROR] !   at …kubejs.recipe.RecipesKubeEvent.discoverRecipes(RecipesKubeEvent.java:219)
[17:21:27] [ERROR] !   at …kubejs.recipe.RecipesKubeEvent.post(RecipesKubeEvent.java:179)
[17:21:27] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.handler$ehl000$kubejs$customRecipesHead(RecipeManager.java:3077)
[17:21:27] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java)
[17:21:27] [ERROR] !   at net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java:36)
[17:21:27] [ERROR] !   at net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$1(SimplePreparableReloadListener.java:19)
[17:21:27] [ERROR] !   at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[17:21:27] [ERROR] !   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:21:27] [ERROR] !   at net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69)
[17:21:27] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
[17:21:27] [ERROR] !   at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
[17:21:27] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
[17:21:27] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
[17:21:27] [ERROR] !   at net.minecraft.client.Minecraft.managedBlock(Minecraft.java:4516)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.loadWorldDataBlocking(WorldOpenFlows.java:201)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.loadWorldStem(WorldOpenFlows.java:142)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.openWorldLoadLevelStem(WorldOpenFlows.java:345)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.openWorldCheckVersionCompatibility(WorldOpenFlows.java:334)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.openWorldLoadLevelData(WorldOpenFlows.java:296)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.openWorld(WorldOpenFlows.java:261)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.joinWorld(WorldSelectionList.java:498)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.mouseClicked(WorldSelectionList.java:481)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.components.AbstractSelectionList.mouseClicked(AbstractSelectionList.java:315)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.components.events.ContainerEventHandler.mouseClicked(ContainerEventHandler.java:38)
[17:21:27] [ERROR] !   at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:98)
[17:21:27] [ERROR] !   at net.minecraft.client.gui.screens.Screen.wrapScreenError(Screen.java:451)
[17:21:27] [ERROR] !   at net.minecraft.client.MouseHandler.onPress(MouseHandler.java:95)
[17:21:27] [ERROR] !   at net.minecraft.client.MouseHandler.lambda$setup$4(MouseHandler.java:202)
[17:21:27] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:98)
[17:21:27] [ERROR] !   at net.minecraft.client.MouseHandler.lambda$setup$5(MouseHandler.java:202)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokeV(Native Method)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[17:21:27] [ERROR] !   at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:162)
[17:21:27] [ERROR] !   at net.minecraft.client.Minecraft.runTick(Minecraft.java:1220)
[17:21:27] [ERROR] !   at net.minecraft.client.Minecraft.run(Minecraft.java:807)
[17:21:27] [ERROR] !   at net.minecraft.client.main.Main.main(Main.java:230)
[17:21:27] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:580)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[17:21:27] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[17:21:27] [ERROR] !   at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
[17:21:27] [ERROR] !   at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)`

**Comment by DarkBladeNemo** [comment]
Just did a quick test. With only this mod and Kubejs installed it will produce the error.

[server.log](https://github.com/user-attachments/files/18263932/server.log)

**Comment by hydroxy7** [comment]
Can confirm I get this same exact error as well.

**Comment by STS15** [comment]
This was a mistaken recipe added for a block in dev.  It will be removed in the next release.  Thanks for letting me know.
